"""add audit logs and finance policies

Revision ID: 2e6072c262e5
Revises: 48f89d0adb6f
Create Date: 2026-08-26 09:11:29.343144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6072c262e5'
down_revision: Union[str, Sequence[str], None] = '48f89d0adb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_policies',
    sa.Column('policy_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_policies_category'), 'finance_policies', ['category'], unique=False)
    op.create_index(op.f('ix_finance_policies_policy_code'), 'finance_policies', ['policy_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Enum('RECONCILIATION_STARTED', 'RECONCILIATION_COMPLETED', 'EXCEPTION_CREATED', 'EXCEPTION_UPDATED', 'EXCEPTION_RESOLVED', 'AGENT_DECISION', 'TOOL_EXECUTED', 'POLICY_CHECK', 'MANUAL_OVERRIDE', name='auditaction'), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'USER', 'AGENT', name='auditactor'), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_agent_run_id'), 'audit_logs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_transaction_id'), 'audit_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_transaction_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_run_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_finance_policies_policy_code'), table_name='finance_policies')
    op.drop_index(op.f('ix_finance_policies_category'), table_name='finance_policies')
    op.drop_table('finance_policies')
    # ### end Alembic commands ###
