"""add reconciliation and exception tables

Revision ID: 48f89d0adb6f
Revises: 287311120852
Create Date: 2026-08-26 09:03:05.334376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f89d0adb6f'
down_revision: Union[str, Sequence[str], None] = '287311120852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliations',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_settlement_match', sa.Boolean(), nullable=False),
    sa.Column('payment_invoice_match', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'MISMATCH', 'RESOLVED', 'ESCALATED', name='reconciliationstatus'), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_transaction_id'), 'reconciliations', ['transaction_id'], unique=True)
    op.create_table('exceptions',
    sa.Column('reconciliation_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('exception_type', sa.Enum('AMOUNT_MISMATCH', 'MISSING_PAYMENT', 'MISSING_SETTLEMENT', 'MISSING_INVOICE', 'FEE_MISMATCH', 'TAX_MISMATCH', 'STATUS_MISMATCH', 'UNKNOWN', name='exceptiontype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='exceptionseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'ESCALATED', 'REJECTED', name='exceptionstatus'), nullable=False),
    sa.Column('agent_decision', sa.Text(), nullable=True),
    sa.Column('agent_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_reconciliation_id'), 'exceptions', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_exceptions_transaction_id'), 'exceptions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_transaction_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_reconciliation_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_reconciliations_transaction_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    # ### end Alembic commands ###
